services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-app
    ports:
      - "8000:8000"
    env_file:
      - ./src/.env
    depends_on:
      - keycloak
      - app-db
    restart: on-failure
    networks:
      - net

  keycloak:
    container_name: keycloak
    image: keycloak
    ports:
      - "9090:9090"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    command: start-dev --http-port=9090 --db postgres --db-url-host keycloak-db --db-username postgres --db-password postgres
    depends_on:
      - keycloak-db
    restart: on-failure
    networks:
      - net

  app-db:
    container_name: app-db
    image: postgres
    ports:
      - "6432:6432"
    environment:
      - PGPORT=6432
      - POSTGRES_PASSWORD=postgres
    restart: always
    networks:
      - net

  keycloak-db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    restart: always
    networks:
      - net

networks:
  net:
    driver: bridge