"""

Revision ID: 7b5efcc408ab
Revises: 4834e5f59642
Create Date: 2025-06-09 17:32:26.902429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b5efcc408ab'
down_revision: Union[str, None] = '4834e5f59642'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=True),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Double(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='datasets'
    )
    op.drop_table('sales')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('transaction_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('sales_pkey'))
    )
    op.drop_table('sales', schema='datasets')
    # ### end Alembic commands ###
