"""

Revision ID: 7b55e2200f9c
Revises: 22dbfa55388c
Create Date: 2025-06-19 21:05:53.500622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b55e2200f9c'
down_revision: Union[str, None] = '22dbfa55388c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('power_ranking', sa.Column('score_differential', sa.Integer(), nullable=True))
    op.drop_column('power_ranking', 'score_diffrential')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('power_ranking', sa.Column('score_diffrential', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('power_ranking', 'score_differential')
    # ### end Alembic commands ###
